### ISSUE TITLE
mem-event-example freezes the guest

### ISSUE THREAD

**Issue by julie-nga** [libvmi/libvmi#1108]
Hello everyone,
I’m encountering a similar issue as described in this previous issue : [https://github.com/libvmi/libvmi/issues/1000](https://github.com/libvmi/libvmi/issues/1000) . My guest VM pauses while running the `mem-event-example` on my VM.
I noticed that this issue was reported three years ago, and since then, there have been updates to the `mem-event-example` to solve it. However, I’m still experiencing this behavior with the latest version of libvmi.

What could be causing the VM to pause unexpectedly?
Has anyone successfully run `mem-event-example` on a similar configuration recently?

**_Setup:_**
**Host OS:** Windows 11
**VM:** Debian 11 (via Vagrant)
**LibVMI version:** Latest from GitHub
**Guest VM:** Windows XP
**Vagrant Setup:** Followed instructions from https://kvm-vmi.github.io/kvm-vmi/master/setup.html#option-1-vagrant-virtual-machine-based-setup

**Comment by tklengyel** [comment]
That example is really just to illustrate the use of the API. From a practical perspective there is no utility to it and depending on what the guest was doing when you started it it could very easily appear to be locked up. What it's doing is removing the execute-permission from the page vCPU 0 is executing from. When a pagefault occurs it relaxes the permission, singlesteps the CPU, then restores the restriction on the memory. This would obviously result in many many VMEXITs for the executing of code from that page. Furthermore, if that page happens to be in the fast-path of the VMs execution, say the page for interrupts, it's pretty much guaranteed to freeze up the VM. Looking at the code it's also unsafe when you have more then 1 vCPU attached to the VM due to race-condition and you really should be using altp2m in that case.

Anyway, don't expect any particular utility from that example, it's just to illustrate the use of the API.
