### ISSUE TITLE
MultiThread

### ISSUE THREAD

**Issue by carttam** [libvmi/libvmi#1109]
Hi, how can I configure libvmi to handle events with multiple threads? Currently, libvmi only responds to each VM exit in a single thread, but I want to utilize multiple threads for better performance.

**Comment by tklengyel** [comment]
Remember that the hypervisor sends event info to LibVMI in a serialized way. On Xen all even info is placed on a single shared memory page (ring page). It also sends an interrupt to LibVMI to notify an event has been placed on the ring. It's a FIFO style mechanism. You can process the events that are already on the ring in any order you want, even multi-threaded, but the hypervisor side is implemented such that it has a single pointer to where the next event should be placed. If the ring becomes full, the hypervisor parks the vCPUs until space gets freed on the ring where the "next pointer" points to, and remember, the ring wraps around. So even if you have events `A, B, C -> wrap around -> D -> next is event should be placed where A is on the ring page`, it doesn't matter if you process B, C & D in a multi-threaded fashion on the LibVMI side, the hypervisor will park future events until you process A as that's where the next event should be placed. It doesn't matter that you have free space somewhere else on the ring. That also means the hypervisor won't process your event responses for already finished events until whatever is "next" in its FIFO queue is marked done.

Redesigning this interface to allow truly multi-threaded processing would require separate pages for each vCPUs or more "fixed" space allocation for each vCPU to be done at initialization time so that events can be processed asynchronously instead of FIFO style. We talked about that multiple times with @andyhhp but -ENOTIME, never got implemented.

**Comment by carttam** [comment]
@andyhhp I would be grateful if you could give me some tips to help me do this
@tklengyel , @andyhhp  Thank you for your help

**Comment by andyhhp** [comment]
In Xen, there's a facility called vm_event which has 3 sub-features.  Monitor, which is what libvmi cares about, Paging (hypervisor paging of guest memory out to disk), and Sharing (Copy-on-Write between VMs).  A lot of details are relevant to all 3, but I'll focus on Monitor specifically.  The name "access" is what Monitor used to be called, and some of that history is still visible.

Inside xen.git, there's https://github.com/xen-project/xen/blob/master/tools/misc/xen-access.c which is a very simple example of the monitor (previously access) interface.  It will need updating as part of your changes to Xen, and is probably easier to work with than a full libvmi stack while you're rearranging the internals.

### Current ring

vm_event rings use Xen's common ring macros.  The ring macros are extreme obfuscation, as can be seen by the expansion of `SHARED_RING_INIT()` and `BACK_RING_INIT()` in `xenaccess_init()` https://github.com/user-attachments/assets/48efd3c9-e4bd-4fc2-909e-c7f99774a90e.

The ring itself is a piece of guest memory.  The position is chosen by the domain builder (hardcoded as gpa 0xfeff9000) and communicated to Xen via `HVM_PARAM_MONITOR_RING_PFN`.  Mapping the ring is a regular foreign_map operation on gfn 0xfeff9.  

The ring is a 4k page, with some metadata at the start (64 bytes), and the remainder (4032 bytes) housing the largest power-of-2 sized array of requests/responses that will fit.  Right now, a `vm_event_request_t` is 400 bytes, so the ring has 8 slots in it.

Monitor events can be synchronous or asynchronous.  Synchronous events pause the triggering vCPU, awaiting a reply.  Asynchronous events put a message in the ring and let the vCPU continue running. 

Notifications are via a single event channel.  Xen sends an event when new requests are available in the ring, and userspace sends an even when new responses are in the ring (synchronous events) or when space has been made (asynchronous events).  Userspace copies the request out of the ring, and for synchronous events, edits it, and copies back into the ring (likely in a different slot).

### QEMU ring

(Because some details are relevant to the suggested design.)

The QEMU ioreq has a slot per vCPU, and a 32-byte structure including an event channel each.  This used to be one of the limits on the number of vCPUs a domain can have (128, = 4k / 32).

Since it's inception, it has been extended to be a multi-page ring using the `XENMEM_acquire_resource` hypercall which is designed to overcome the flaws of having the ring live in guest memory, and provide a way to share pages between Xen and userspace without them ever having been part of the domain.

### Issues with the current monitor ring

The ring is trying to server two purposes.  The synchronous side, where the vCPU waits until a reply from userspace, and the asynchronous side where Xen is a producer and userspace is a consumer.

With only 8 slots, the ring can be full when a vCPU has generated a new event.  Right now that leads to some very hairy logic (xen/common/wait.c and the thing I'm longing to delete) which is incompatible with livepatching.  wait.c stashes a copy of the active stack, and livepatching relies on all vCPUs to have unwound their stack for safety.

The ring being part of guest memory leads to several problems.  First, the guest could write into it.  This is solved by shooting the page out of the guest after dom0 has mapped it, which prevents the guest accessing it, but leaves the page in limbo as far as Xen's memory accounting is concerned.  Also, it shatters any HAP superpages that might have been backing the range.

Also, being part of guest memory leads to a second issue; what happens if the page isn't there to be mapped in the first place?  This too is bodged around, with the mapping logic populating the page just to map it and shoot it out again, but that is a TOCTOU race with the VM's memory allocation limit, and if the VM's balloon driver is being aggressive, can result in a failure to establish the ring entirely.  This is a problem when (re-)attaching VMI to an already-running VM.

### Suggested design

The synchronous and asynchronous usecases are entirely different and should be treated separately.

The synchronous part should be a slot-per-vCPU like the QEMU ring, but with a bit more flexibility.  There should be a fixed section at the front (metadata, geometry/etc) and then a fixed location for each vCPU's data.  At this point we can also have an event channel per vCPU (like QEMU) which gets you the multithreading property.

The asynchronous part should be a multi-page-capable ring with a minimum number of entries set by the vCPU count.  Critically, this means Xen can guarantee there is always space by writing an entry, and then pausing the vCPU if there is insufficient space remaining for $N-1 vCPUs to write an entry too.  As a result, we can remove all of wait.c.  Userspace can choose a ring large enough for the expected latency of getting rescheduled to consume a bunch of entries.

These rings should be implemented using `XENMEM_acquire_resource` so they're entirely outside of the guest memory.


I realise this is quite a large braindump already, and I haven't even got started on the specifics of implementation.  Before I do, does this broadly make sense?

**Comment by tklengyel** [comment]
@andyhhp This is the most comprehensive documentation of the current vm_event implementation and it's major flaws/bottlenecks that I've ever seen! I think this would be very worthwhile to copy into the Xen tree as well under `docs/misc`! :)
