### ISSUE TITLE
Issues accessing memory in guests with > 2GB of RAM

### ISSUE THREAD

**Issue by bdpayne** [libvmi/libvmi#258]
From a mailing list conversation, it sounds like we may have an issue accessing memory in guests with more than 2GB of RAM.  I'm not sure of the root cause, but this is a placeholder to investigate.

Mailing list discussion is at:
https://groups.google.com/forum/#!topic/vmitools/mJKxLohpJ78

**Comment by awsaba** [comment]
[This gist](https://gist.github.com/awsaba/5c807a8d07582c0f5770) shows the issue for Xen HVMs.  In particular Win 7 x64 uses pages in the 0x00100000-0010fbff range, which fail in get_memory() as being above the size of the RAM calculated using memkb. Changing that check for live VMs to use the result of "xc_get_maximum_gpfn()" should fix the issue for live VMs.

I'm not sure how to address the API to expose this for tools such as `dump-memory` itself, since using `max_gpfn` almost doubles the size for the 2GB VM, for not a lot of pages.  Options I see are:
1. Use the E820 map to stop dumping when the remaining regions are reserved
2. Support (and encourage the use of) non-raw, formatted files that leave out the 0's for unmapped pages.
3. Warn people in the documentation, and let them truncate stuff they don't need from the end of the file if they don't need it.

**Comment by tklengyel** [comment]
Is there an API to access the E820 map?

**Comment by awsaba** [comment]
I saw it while skimming `xenctrl.h` (which is how I found `xc_get_maximum_gpfn()`), which is the extent of what I know about, or if it will be populated for guests using EFI based BIOS, etc.

**Comment by tklengyel** [comment]
Ah, excellent: xc_get_machine_memory_map

**Comment by tklengyel** [comment]
Yea, we should just use this map and return VMI_FAILURE for regions known to be inaccessible.

**Comment by smaresca** [comment]
VMI_FAILURE or a new status_t to indicate inaccessible memory?

**Comment by tklengyel** [comment]
What I meant is that there is no reason to actually try to map memory when we already know its inaccessible. We should use xc_get_maximum_gpfn() for the upper bound and skip the holes automatically for performance boost. We have similar holes on guest memory in ARM as well that we could automatically return VMI_FAILURE for (with probably a debug message saying the access is skipped because its a known hole). I think for dump-memory it's fine to have the memory with the holes in it, even if that means that the file is going to be bigger then necessary.

**Comment by smaresca** [comment]
Right certainly, but useful to indicate to the caller so (for example)
those regions can be padded with zeros unanimously

**Comment by tklengyel** [comment]
That's exactly what's dump-memory doing already. Failed to read page? Pad with zero. https://github.com/libvmi/libvmi/blob/master/examples/dump-memory.c#L87

**Comment by tklengyel** [comment]
Sorry, read_page doesn't actually return status_t, it returns void*, so we could just return NULL in xen_get_memory_pfn without running xc_map_foreign_range, which is quite costly.

**Comment by tklengyel** [comment]
Hm, unfortunately xc_get_machine_memory_map is not available for HVM domains..

**Comment by tklengyel** [comment]
In order to be able switch to xc_get_maximum_gpfn we need to check for which version of it we have. In 4.6 it has been changed from `int xc_domain_maximum_gpfn(xc_interface *xch, domid_t domid);` to `int xc_domain_maximum_gpfn(xc_interface *xch, domid_t domid, xen_pfn_t *gpfns);`

**Comment by tklengyel** [comment]
Maybe have another API for getting max accessible pfn, that would translate internally to xc_domain_maximum_gpfn.

**Comment by smaresca** [comment]
@awsaba satisfactorily addressed by PR282 ?

**Comment by awsaba** [comment]
Addressed for Xen HVM in #282, updated title to reflect that I've really only addressed it for Xen HVMs. I'm going to close this one and suggest that new ones for other platforms are opened as people have resources to look at them.
