### ISSUE TITLE
Unify vmi_init functions

### ISSUE THREAD

**Issue by mfusaro** [libvmi/libvmi#287]
Would like to unify the vmi_init series of functions to just vmi_init() so we don't have so many methods of initializing the library. We are already passing the flags and info we need in the vmi_init_custom to make the decisions about the init and having this many init functions is going to confuse people. Especially newer users.

**Comment by awsaba** [comment]
#249 is an easy way to at least get rid of one version of vmi_init_complete, which will make it easier to rename the rest.

I think it would be less confusing to rename them to things like vmi_init_physical() instead of partial, vmi_init_virtual() or ...paging() instead of complete, and maybe full() to mean to start from scratch and do both?

**Comment by tklengyel** [comment]
We already have vmi_init_paging() so I think it would make sense to introduce the following functions
 - vmi_init_physical
 - vmi_init_events
 - vmi_init_os: This would initialize the operating-system specific components. These are required for all functions with _va, ksym2v, uv2p, kv2p

**Comment by tklengyel** [comment]
For planned VirtualBox driver extra input is going to be required, so another function vmi_init_hypervisor will be necessary.
