### ISSUE TITLE
Does libvmi work on a aarch64 host?

### ISSUE THREAD

**Issue by targetnull** [libvmi/libvmi#319]
I want to install libvmi in a 64bit linux running on a board whose architecture is aarch64(This linux is meant to be a host, not a guest).

But I only find three architecture in the [source code](https://github.com/libvmi/libvmi/blob/master/libvmi/arch/arch_interface.c#.L46), does it mean that I need additional work to install it on aarch64, or it doesn't support aarch64 right now?

Thanks.

**Comment by tklengyel** [comment]
If the host is running in aarch64 mode thats ok. The support in LibVMI is about the guest paging. I haven't checked how different aarch64 paging is but it could be quite easily added either way, we just haven't had access to hw before to implement/test it on.

**Comment by targetnull** [comment]
I see, do you mean that installing it on a aarch64 host is OK but running a aarch64 guest is not implemented yet?

**Comment by targetnull** [comment]
Thanks, I may not need to run a aarch64 guest at present.

**Comment by targetnull** [comment]
Hi, @tklengyel @drakvuf-jenkins 

Sorry but I forgot one question when I closed this issue. Just to be sure, which were you referring when you say that it supports aarch64, in KVM or Xen? I'd like to use it on kvm-arm, but it seems not to support it.

Thanks

**Comment by tklengyel** [comment]
What I meant is that you can compile and run LibVMI on an aarch64 host. You won't be able to introspect an aarch64 guest. As for what hypervisor you use it with, it has only been tested with Xen on ARM and I don't think it will work with KVM.

**Comment by targetnull** [comment]
Really unluck...
My teammate and I have been looking for a lib to simplify the introspection. Do you know any other project that might supports KVM ARM?

**Comment by noxdafox** [comment]
Hi.

I just noticed this on the new [QEMU 2.6 changelog](http://wiki.qemu.org/ChangeLog/2.6).

>  KVM
>  Support for guest debugging (software and hardware breakpoints, single step) on AArch64

**Comment by tklengyel** [comment]
That's an interesting find. It would be nice to make LibVMI's event wrapper
tap into that on aarch64. However, singlestepping on aarch64 doesn't seem
to be stealthy as it relies on modifying the in-guest singlestep bits and
preventing the guest itself from using it. Software breakpoints look very
similar to how it supposed to work on x86. Apparently there is a debug bit
that can be configured to trap these to the hypervisor (MDCR_EL2.TDE):

TDE

Trap software debug exceptions:
0 Has no effect on software debug exceptions.1 Route Software debug
exceptions from Non-secure EL1 and EL0 to EL2. Also enables traps on all
debug register accesses to EL2.

If HCR_EL2.TGE is 1, then this bit is ignored and treated as though it is 1
other than for the value read back from MDCR_EL2.This bit resets to 0.
So that's quite handy.

**Comment by tklengyel** [comment]
PR #343 added support for ARM64 guests.
