### ISSUE TITLE
Support for Linux KASLR.

### ISSUE THREAD

**Issue by MikePetullo** [libvmi/libvmi#397]
I had trouble using libvmi with Linux 4.7.3, as discussed on the libvmi mailing list (https://groups.google.com/forum/#!topic/vmitools/f-LkOKb8bPQ). At least two people seem to have had trouble using libvmi with Linux 4.7.3.

**Comment by tklengyel** [comment]
The problem seems to be with walking the pagetables. Here is a debug log:

./examples/process-list debian-stretch
LibVMI Version 0.11.0
--found Xen
LibVMI Mode 2
--completed driver init.
--got id from name (debian-stretch --> 10)
**set image_type = debian-stretch
**The running Xen version is 4.7
**set hvm to true (HVM).
--xen: setup live mode
**set allocated_ram_size = 1004a000, max_physical_address = 0xff001000
**set pae = 1
**set pse = 1
**set lme = 1
**IA-32e paging
**sanity checking cr3 = 0x0000000007db4000
--succesfully completed architecture init.
--looking for config file at /root/etc/libvmi.conf
--looking for config file at /etc/libvmi.conf
**Using config file at /etc/libvmi.conf
**set os_type to unknown.
**set vmi->kpgd (0x0000000007db4000).
Process listing for VM debian-stretch (id=10)
--SYM cache set init_task -- 0xffffffff81a0d500
--PTLookup: lookup vaddr = 0xffffffff81a0d9a0
--PTLookup: dtb = 0x0000000007db4000
--MEMORY cache set 0x7db4000
--xen_get_memory_pfn success on pfn=0x7db4
--PTLookup: pml4e_address = 0x0000000007db4ff8
--MEMORY cache set 0x5a09000
--xen_get_memory_pfn success on pfn=0x5a09
--PTLookup: pdpte_address = 0x0000000005a09ff0, pdpte_value = 0x0000000005a0a063
--MEMORY cache set 0x5a0a000
--xen_get_memory_pfn success on pfn=0x5a0a
--PTLookup: pde_address = 0x0000000005a0a068, pde_value= 0x0000000000000000
--PTLookup: paddr = 0x0000000000000000
--PTLookup: lookup vaddr = 0xffffffff81a0db50
--PTLookup: dtb = 0x0000000007db4000
--MEMORY cache hit 0x7db4000
--PTLookup: pml4e_address = 0x0000000007db4ff8
--MEMORY cache hit 0x5a09000
--PTLookup: pdpte_address = 0x0000000005a09ff0, pdpte_value = 0x0000000005a0a063
--MEMORY cache hit 0x5a0a000
--PTLookup: pde_address = 0x0000000005a0a068, pde_value= 0x0000000000000000
--PTLookup: paddr = 0x0000000000000000
Failed to find procname

**Comment by tklengyel** [comment]
So it seems the addresses in the System.map are off to what is being used at runtime.

According to the System.map:

- ffffffff81a0d500 D init_task

According to /proc/kallsyms

- ffffffff85a0d500 D init_task

**Comment by tklengyel** [comment]
So it seems like Linux 4.7 has kaslr enabled by default. The only workaround for now is to disable kaslr in the guest by adding `nokaslr` to the boot option.

**Comment by tklengyel** [comment]
Preliminary support is available in the following branch for 64-bit guests: https://github.com/tklengyel/libvmi/tree/linux_aslr

**Comment by MikePetullo** [comment]
On Thu, Oct 06, 2016 at 01:35:31PM -0700, Tamas K Lengyel wrote:
> Preliminary support is available in the following branch for 64-bit
> guests: https://github.com/tklengyel/libvmi/tree/linux_aslr

Wow!

I would like to make sure I understand this new code. It seems to check
each page for the string "swapper" (idle process) at the process-name
offset of an address potentially corrsponding to the idle process's
task structure.

At first I wondered what is special about the "init_task" symbol that we
could rely on its position despite KASLR. But, it appears this merely
requires KASLR not support sub-page random ofsets. Put another way,
the KASLR offset must be a multiple of the page size. I think this is
the case; am I right? The closest statement I have found is a mention
of 2M alignment at https://lwn.net/Articles/569635/.

It also seems that the string "swapper" *could* exist in kernel memory
at the expected offset conincidentaly and not as a process name. This
could result in a miscalculation of the KASLR offset, right?

-- 
Mike

:wq

**Comment by tklengyel** [comment]
Right, Linux's KASLR just shifts the kernel base address by random number of pages. So by looping through all kernel pages mapped into a process we can simply find what that random was. We can really use any symbol for this, init_task just has been convenient as we already gather its offset. For validating init_taks, beside checking for "swapper", we also check that the PID is 0 at the right offset. We can add more checks if needed but AFAICT this works just fine.

**Comment by richarduu** [comment]
Hi Tamas,
    I come to look at this piece of code in detail, because of the problem of rekal profile for kernel version 4.13.0+ (["Failed to determine init_task"](https://github.com/tklengyel/drakvuf/issues/381)).
    I get "**failed to determine KASLR offset" somehow after using the approach mentioned in [google/rekal#337](https://github.com/google/rekall/issues/337)
    And I find using this approach to get the kaslr_offset may fail in some case, at least for x86_64 and kernel version 4.13.0+. (maybe again because of other problems in the profile though)
    It makes more than 10000 attempts and finally fails to "determine KASLR offset".
        
    But actually, determining KASLR offset in x86_64 can be much simpler, because the kernel memory layout is clearly stated in the official [documentation](https://www.kernel.org/doc/Documentation/x86/x86_64/mm.txt). 
    What we need to do is just trying to get the physical page of the first page mapped of the kernel text mapping. We can get the offset once we get the first kernel text page mapped. Because in the range of 0xffffffff80000000 ~ 0xffffffffa0000000 there is only kernel text, and the first page found mapped beginning from 0xffffffff80000000 is the start of the kernel text mapping, thus we can get the kaslr offset.
        
    I did not figured out why the original approach fails in the case when it is 4.13.0+. But I did manage to make it work using this code below. 
    I am not sure why you do not use this approach, maybe out of consideration of portability for other architection?

    diff --git a/libvmi/os/linux/core.c b/libvmi/os/linux/core.c
    index 788a7e9..b58104b 100644
    --- a/libvmi/os/linux/core.c
    +++ b/libvmi/os/linux/core.c
    @@ -253,6 +253,22 @@ static status_t init_task_kaslr_test(vmi_instance_t vmi, addr_t page_vaddr)
         return ret;
     }   
         
    +status_t kaslr_offset_found_aarch64(vmi_instance_t vmi){
    +    addr_t vaddr, paddr;
    +    addr_t ktext_start = 0xffffffff80000000;
    +    addr_t ktext_end = 0xffffffff80000000 + (1024*1024*1024);
    +    linux_instance_t linux_instance = vmi->os_data;
    +    for (vaddr = ktext_start; vaddr < ktext_end; vaddr += 0x200000){
    +        if (vmi_translate_kv2p(vmi, vaddr, &paddr) == VMI_SUCCESS){
    +            linux_instance->kaslr_offset = vaddr - ktext_start;
    +            vmi->init_task += linux_instance->kaslr_offset;
    +            dbprint(VMI_DEBUG_MISC, "**calculated KASLR offset: 0x%"PRIx64"\n", linux_instance->kaslr_offset);
    +            return VMI_SUCCESS;
    +        }   
    +    }   
    +    return VMI_FAILURE;
    +}  
    +   
     status_t init_kaslr(vmi_instance_t vmi)
     {   
         /*  
    @@ -268,6 +284,10 @@ status_t init_kaslr(vmi_instance_t vmi)
         if ( VMI_SUCCESS == vmi_read_32(vmi, &ctx, &test) )
             return VMI_SUCCESS;
         
    +    if ( VMI_SUCCESS == kaslr_offset_found_aarch64(vmi) )
    +        return VMI_SUCCESS;
    +    return VMI_FAILURE;
    +   
         status_t ret = VMI_FAILURE;
         linux_instance_t linux_instance = vmi->os_data;
         GSList *loop, *pages = vmi_get_va_pages(vmi, vmi->kpgd);

**Comment by tklengyel** [comment]
Please open a PR with the changes. There was no deeper consideration in the current KASLR search method other than that it seemed to be a convenient and easy method to use. If it no longer works on newer kernels for some reason, switching to something else is fine.

**Comment by richarduu** [comment]
Yep, PR created.
