### ISSUE TITLE
vmi_read_va

### ISSUE THREAD

**Issue by mbhatt1** [libvmi/libvmi#525]
what is the byte written argument in this method? How do I use it? I am trying to write 32 bytes of data at a certain location in memory.

**Comment by smaresca** [comment]
The bytes_written parameter of the vmi_write family of functions is an optional output parameter. If you pass a pointer to a size_t variable, the write function will store the number of bytes written at the target memory location.  Otherwise, pass NULL for that argument.

The bytes_read parameter of the vmi_read family of functions behaves in the same manner.
