### ISSUE TITLE
Expose an environment variable to enable LibVMI debug output

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#649]
Hi,

The current way of enabling LibVMI debug output is to enable the desired verbosity in `libvmi/debug.h` and recompile.

This process can become tedius while developing and debugging small VMI applications to quickly localize the problem.

Also, if LibVMI will be distributed as a packaged library, you don't want to clone `libvmi`, compile it (installing the dev tools) and install it, only to get a more verbose output in order to understand why the driver initialization fails for example.

Could we check for a specific environment variable to enable verbose output ?
It could be enabling every log messages `__VMI_DEBUG_ALL`, at the beginning, or nothing, with `LIBVMI_DEBUG=1`

-> What do you think ?
-> How difficult would it be to implement ?

Thanks.

**Comment by tklengyel** [comment]
The current way actually compiles the debug code out when not needed for optimal performance. Xen does the same. If it can be shown that the performance is not impacted I would consider this a good idea.

**Comment by Wenzel** [comment]
Actually do we have a test suite to measure `libvmi`'s performance ?

**Comment by tklengyel** [comment]
Not at the moment. One of my GSoC student is working on benchmarking right now but not sure if he will be able to contribute a test suite. /cc @scorpionzezz

**Comment by scorpionzezz** [comment]
hi, why not. But how it should be implemented?
Just now I did compare the performance with safety check and not safety check. I hook write and open system call and try to download a 2MB file using wget (local network, so network delay can be excluded) after 100 iterations it took (in average) 0.1494s and 0.12247s for with safety check and without respectively.

**Comment by tklengyel** [comment]
How it should be implemented is an open question :) I would prefer if we had something that could be run in Travis and would run for every PR.

**Comment by mtarral** [comment]
Hi,

this is a proposed implementation of toggling the debug output via an environment variable

First adding a new build option is necessary, disabled by default, so that
there will be no performance hit for common users:
~~~cmake
option(ENV_DEBUG "Toggle the debug output via LIBVMI_DEBUG environment variable" OFF)
~~~

Then making this build option accessible in the C code in `config.h.in`

~~~C
/* Toggle debugging via environment variable LIBVMI_DEBUG */
#cmakedefine ENV_DEBUG
~~~

And finally we can update `convenience.c` where the `dbprint` function is defined

~~~C
if (category & VMI_DEBUG && ENV_DEBUG_COND) {

}
~~~

Where our newly added condition `ENV_DEBUG_COND`

~~~C
#ifdef ENV_DEBUG
# define ENV_DEBUG_COND getenv("LIBVMI_DEBUG")
#else
# define ENV_DEBUG_COND true
#endif
~~~

So by default, `ENV_DEBUG` being `OFF`, the condition evaluates to `true`, optimized by the compiler to nothing.

I wanted to proposed that here first before making a PR, since the code is small, and we start brainstorming on the best implementation.

**Comment by tklengyel** [comment]
That sounds good to me

**Comment by smaresca** [comment]
I like it!

**Comment by mtarral** [comment]
I believe we can close this issue.
