### ISSUE TITLE
Cannot Run Any Example

### ISSUE THREAD

**Issue by Lixiaomingg** [libvmi/libvmi#659]
Hi,
I faced this error whenever I want to run the example . Could you tell me what's wrong with this error log ?

```
work@ubuntu:~/lib/libvmi-master/examples$ sudo ./vmi-process-list ubuntu 
--found KVM
LibVMI Version 0.13.0
LibVMI Driver Mode 1
--completed driver init.
--got id from name (ubuntu --> 11)
**set image_type = ubuntu
--libvirt version 3000000
--qmp: virsh -c qemu:///system qemu-monitor-command ubuntu '{"execute": "query-version"}'
--Checking QEMU version string...
--Fail: incompatibility between libvmi and QEMU request definition detected
Failed to init LibVMI library.
```

Thanks!

**Comment by Wenzel** [comment]
Hi,

this error is originated from here:
https://github.com/libvmi/libvmi/blob/69b31982bcc136ddcdff07c4cf803f6343a20468/libvmi/driver/kvm/kvm.c#L1482

You need to make sure that you have installed QEMU 2.8.0 with the libvmi memory access patch.
this patch will provide a set of headers that have to be detected by libvmi configure script, to define `HAVE_LIBVMI_REQUEST`:

configure:
https://github.com/libvmi/libvmi/blob/master/configure.ac#L231

I suppose your custom QEMU is not installed system wide, that's why LibVMI cannot find the headers, either in /usr or /usr/local

**Comment by Lixiaomingg** [comment]
I can sure that i have installed QEMU 2.8.0 with the libvmi memory access patch.
I search the headers and get the result:
```
work@ubuntu:~/lib$ sudo find / -name libvmi_request.h
/usr/local/include/qemu/libvmi_request.h
/home/work/lib/qemu-2.8.0/libvmi_request.h
```

I check the version of QEMU and get the result:
```
work@ubuntu:~/lib/libvmi-master/examples$ sudo virsh -c qemu:///system qemu-monitor-command ubuntu '{"execute": "query-version"}'
{"return":{"qemu":{"micro":0,"minor":8,"major":2},"package":""},"id":"libvirt-15"}
```
I check the code in` libvmi/libvmi/driver/kvm/kvm.c`,
```
    // QEMU should be < 2.8.0
    if (major >= 2 && minor >= 8) {
        dbprint(VMI_DEBUG_KVM, "--Fail: incompatibility between libvmi and QEMU request definition detected\n");
        goto out_error;
    }
```
Does it mean that i should't install QEMU 2.8.0 and should replace QEMU 2.8.0 with lower version ?

**Comment by Wenzel** [comment]
Hi
I think you just have to reconfigure Libvmi, and recompile it.

I suppose you compiled it before installing the modified QEMU., therefore it couldn't detect the headers.

**Comment by Lixiaomingg** [comment]
Hi 
The problem has been solved! 
Thanks !

**Comment by Wenzel** [comment]
@Lixiaomingg could you close the issue if everything is solved ?
thanks for confirming.
