### ISSUE TITLE
CMake doesn't disable components automatically

### ISSUE THREAD

**Issue by tklengyel** [libvmi/libvmi#730]
The cmake configuration doesn't automatically disable compiling parts of LibVMI based on the architecture and/or the availability of packages. For example, on ARM it should not build the Bareflank driver. Also, flex and json-c should be optional packages and cmake should disable the parts of LibVMI that depend on them (flex -> libvmi.conf, json-c -> rekall profiles/kvm/bareflank).

**Comment by tklengyel** [comment]
Paging @Wenzel

**Comment by Wenzel** [comment]
@tklengyel trying to build libvmi on another machine gives me errors with KVM driver.
With a closer look, the CMake code i added is not doing what I intended to do.
`set(ENABLE_KVM OFF)` apprently doesn't disable the option in the parent scope, and `ENABLE_KVM` = 1 in the `config.h` (even afer moving `configure_file` command after `add_subdirectory(libvmi)`

i'm investigating

**Comment by Wenzel** [comment]
I have the fix, you need to replace:
- https://github.com/libvmi/libvmi/blob/master/libvmi/CMakeLists.txt#L65
- https://github.com/libvmi/libvmi/blob/master/libvmi/CMakeLists.txt#L103
- https://github.com/libvmi/libvmi/blob/master/libvmi/CMakeLists.txt#L117

with `set(ENABLE_XXX OFF CACHE BOOL "Enable XXX" FORCE)`

I can't make the PR right now, so if you can do it, otherwise i will push this week-end.

**Comment by tklengyel** [comment]
I'll wait for your PR
