### ISSUE TITLE
VMI_ERROR: process_cb_response on breakpoint-emulate-example.c

### ISSUE THREAD

**Issue by panicos** [libvmi/libvmi#998]
Hi guys,

My host is running Ubuntu and my guest VM is running windows 10 and it is using the bare metal setup Qemu-KVM.
I am executing the breakpoint-emulate-example.c using the following arguments:

`./breakpoint-emulate-example win10 NtOpenFile 3 /tmp/introspector`

Everything works great up to the point where the substituted instruction needs to be emulated after the interrupt callback returns.
When the callback returns with `VMI_EVENT_RESPONSE_SET_EMUL_INSN` the following error gets created and the instruction fails to get emulated.

`VMI_ERROR: process_cb_response: KVM - unhandled event reponse 256`

I have traced this back to https://github.com/libvmi/libvmi/blob/3f5b0d5b3cef8639df4cd7ff52d42e04baf262fd/libvmi/driver/kvm/kvm_events.c#L189

It seems like there is no case for `VMI_EVENT_RESPONSE_SET_EMUL_INSN`.

Do you have any idea why this happens and how to properly solve this?

Thank you in advance for your help!

**Comment by Wenzel** [comment]
Hi @panicos ,

this is expected on KVM.
The error is `unhandled event response 256`, which corresponds to `VMI_EVENT_RESPONSE_SET_EMUL_INSN` enum.
This event response isn't implemented in the KVM driver since this feature isn't available in KVM-VMI today.

You can refer to this README to better understand which features are available:
https://github.com/libvmi/libvmi/tree/master/libvmi/driver/kvm

**Comment by panicos** [comment]
@Wenzel thank you for your fast response! 
Thank you for the link, I should have realized it was not supported.
I have assumed it was supported because it was part of the example.
I will close the issue.
